### ISSUE TITLE
Tests can't be run through tape-run with phantomjs

### ISSUE THREAD

**Issue by lukekarrys** [AmpersandJS/ampersand-subcollection#17]
It'd be nice if tests could be run like this: browserify test/* | tape-run | tap-spec, but they fail because `Object.defineProperty` doesnt work well in phantomjs: ariya/phantomjs#11856

Similar to https://github.com/AmpersandJS/ampersand-collection/issues/23

**Comment by wraithgar** [comment]
@lukekarrys it's been awhile since we talked about this issue is there any update?

**Comment by lukekarrys** [comment]
I'll take a look, might be worth seeing if phantom v2 works with this.

**Comment by wraithgar** [comment]
THis module's deprecated now, let's focus on other things ;)
