### ISSUE TITLE
The sort event is constantly triggered, even when a model is just added.

### ISSUE THREAD

**Issue by latentflip** [AmpersandJS/ampersand-subcollection#23]
Currently any change to a subcollection triggers a sort, even if no comparator is defined on the subcollection. This is a) different to how a collection works, b) means excessive dom manipulation in collection views when rendering subcollections.

It's caused by this line: https://github.com/AmpersandJS/ampersand-subcollection/blob/master/ampersand-subcollection.js#L164

Now, what to do about it. We could check if the subcollection has a comparator and only trigger sort if it does. But what happens if the parent collection has a comparator? At the moment they aren't kept in sync. Should they be?

**Comment by aaronmccall** [comment]
@latentflip, would #37 resolve the issue you were having?

**Comment by wraithgar** [comment]
This should be solved if you use ampersand-filtered-subcollection and/or ampersand-paginated-subcollection
