### ISSUE TITLE
transform?

### ISSUE THREAD

**Issue by contra** [AmpersandJS/ampersand-subcollection#31]
There is a good way to filter out items in a collection based on a function, but what about transforming? This could be done on parent collection update or even done lazily on access.

This would basically be like creating a new view of a collection's data. A basic example of how this could look:

```js
var Movies = new Collection({movie object whatever});

var MoviesWithPeople = new SubCollection(Movies, {
  // map takes in a model, returns a model
  transform: function(movie){
    var newMovie = transformMovieSomehow(movie);
    return newMovie;
  }
});
```

**Comment by aaronmccall** [comment]
There is already a map method on subcollection, @contra. Are you saying you'd like to be able to define a function for models to be mapped through when the subcollection initializes?

**Comment by contra** [comment]
@aaronmccall Yep. On initialization or (if possible) on access of a model (through .at, .map, .each, etc.)

**Comment by aaronmccall** [comment]
@contra, I agree that the concept could be very useful. I'd say that `map` isn't necessarily the best name for it given that there is already a `map` that means something else. It seems to me that `transform` is more directly the concept that you're describing.

**Comment by contra** [comment]
@aaronmccall Yep, transform fits better IMO

**Comment by aaronmccall** [comment]
@contra, I'd say we need to get some input from @AmpersandJS/owners before moving forward on this.

**Comment by contra** [comment]
Any word on this? Need it for some tooling we are working on.

**Comment by kamilogorek** [comment]
I could agree that it might be actually useful in some scenarios and it shouldn't be huge code overhead if we'd want to implement this.

**Comment by HenrikJoreteg** [comment]
@contra i'm quite curious about your use case here. What sort of transformations are you wanting to do? Also, the fact that we'd now be keeping a set of copied, cached objects doesn't quite seem to fit what I imagined sub collections to be used for. 

Not to say it couldn't be done, just dont' understanding what you're wanting to do with it.

**Comment by contra** [comment]
@HenrikJoreteg A collection view that has a collection of models, and a subcollection of item views. The item views are just a map of the models to item views, and need to stay updated when the other collection updates.

Right now I am setting up listeners for any change events on the main collection and then triggering the map. I think it could be done a lot more efficiently with this feature.

**Comment by HenrikJoreteg** [comment]
@contra the way what you're describing is usually done is creating a sub-collection based on your underlying collection and then passing that subcollection to: http://ampersandjs.com/docs#ampersand-view-rendercollection

Render collection just takes a `view` that you want to use for each item in the sub-collection and then handles everything else. If this doesn't suit your use case we can re-open this. But I feel like keeping another set of transformed objects in sync with the underlying collection is going to potentially be problematic.

**Comment by contra** [comment]
@HenrikJoreteg I'm not using ampersand for rendering, we are using react views. I think the fact that you also had this use case validates my concern that this should exist.

**Comment by HenrikJoreteg** [comment]
If you're using react views, wouldn't you just loop through sub-collection to create react components? Something like:

```js
var React = require('react');
var app = require('ampersand-app');
var MyItemComponent = require('../components/item');

module.exports = React.createClass({
    displayName: '',
    render: function () {
        return (
            <div>
                  {app.stuff.subCollection.map(function (model) {
                      return <MyItemComponent model={model} key={model.id} />
                  })}
            </div>
        );
    }
});

```

**Comment by HenrikJoreteg** [comment]
When i re-read my original response it sounded a bit rude. That wasn't my intent, sorry. I'm still trying to understand what exactly you're trying to do.

**Comment by contra** [comment]
@HenrikJoreteg That is what we're doing right now but there would be performance improvements with transform. If only one item changes you only reconstruct with MyItemComponent one time whereas with the current impl you reconstruct every item every time. If the items reshuffle you don't even reconstruct one time.

**Comment by contra** [comment]
We have a working implementation that does exactly what you are saying but this issue being solved would be a performance improvement not only for our stuff but for your collection rendering as well.

**Comment by HenrikJoreteg** [comment]
Ahh, ok. So, couldn't you also, within `MyItemComponent` listen for `change` and call `forceUpdate` instead of re-rendering the whole list? Then just re-render the list on `add`/`remove`?

**Comment by HenrikJoreteg** [comment]
of course if the change affects the position, that'd still be an issue.

**Comment by contra** [comment]
@HenrikJoreteg Each item is responsible for its own re-rendering on data changes but when the collection is updating (either sorting, filtering, new limit, etc.) the whole thing gets computed every time even when the same items are reused.

**Comment by HenrikJoreteg** [comment]
right, ok and this is causing performance problems, currently? So if you had a transform function how would you write the code in your app?

**Comment by contra** [comment]
```js
var sub = new SubCollection({
  collection: collection,
  transform: function(m) {
    return itemView({model: m}); 
  }
});
```

**Comment by HenrikJoreteg** [comment]
and then how would you use it in the React view?

**Comment by contra** [comment]
Would you like to have this conversation somewhere else? I can give you the low-down on the entire framework and walk through the code with you if you would like but IMO it isn't relevant to this issue.

If the concept of a subcollection that can act as a map seems so far-fetched and insane I can just fork or write a wrapper library to handle this case. It seemed natural for it to be a part of subcollection which is why I opened the issue but if you feel otherwise and need an extremely solid case to think about adding it maybe I'm barking up the wrong tree.

**Comment by HenrikJoreteg** [comment]
It's not crazy or far fetched, being able to map other instances makes sense and now that I see the problem you're having it makes sense. Not trying to drill you, just wanted to understand where you were coming from. If you want to take a stab an an implementation and send a PR, that'd be cool. 

You may want to jump into the gitter channel: https://gitter.im/AmpersandJS/AmpersandJS

**Comment by HenrikJoreteg** [comment]
Thanks for taking the time to explain, reopening...

**Comment by contra** [comment]
@HenrikJoreteg As a quick run-down: Each collection view has access to the subcollection via `this.items`. When the subcollection updates it triggers a re-render with a new computed (transformed) `this.items`.

**Comment by HenrikJoreteg** [comment]
Cool, I like it.

**Comment by wraithgar** [comment]
Some of the over-eventing may have been solved via ampersand-filtered-subcollection.  If you do end up making a PR please be aware that this lib has been deprecated in favor of ampersand-filtered-subcollection and ampersand-paginated-subcollection.
