### ISSUE TITLE
O(n^2) execution time for runFilters

### ISSUE THREAD

**Issue by legastero** [AmpersandJS/ampersand-subcollection#41]
The current implementation of runFilters is O(n^2) based on the size of the parent collection.

It is being called liberally for common events like add and remove that shouldn't need as much processing.

Consider fetching and setting 100+ models at once with a moderately expensive filter.

**Comment by legastero** [comment]
Er, runFilters is O(n), which gives O(m^2) when setting a collection with m items

**Comment by wraithgar** [comment]
Here's the little scratchpad we were using last night to debug this http://code.gar.zone/?gist=50df77da0146ea2afaa0

**Comment by wraithgar** [comment]
You'll see that each subcollection gets its filter run n^2+n times where n is the length of its parent.

**Comment by aaronmccall** [comment]
Debounce `_onCollectionEvent`?

**Comment by legastero** [comment]
Debouncing/throttling would fix performance to be no worse than `num-inserted-items * Xms` (good for expensive filters), but it would also mean performance can't be better than Xms (bad for cheap filters), because it will always be debounced/throttled when adding multiple items via set().

It also doesn't solve the problem that `_runFilters` is O(n) even when adding/removing a single item to the parent collection, since that would still be a single `_onCollectionEvent` call.

That said, it would be worth a try to get some data on performance impact.

**Comment by aaronmccall** [comment]
Maybe the answer is to do collection API parity (add, remove, set, etc.) on subcollection and have a little machinery under the hood to prevent the filter craziness.

**Comment by wraithgar** [comment]
That's what @legastero and I have talked about and are starting to whiteboard. I have a branch where I'm trying to hammer out some of this, please consider this problem in progress.

**Comment by aaronmccall** [comment]
@wraithgar, feel free to call on me for help with it—coding, testing, etc.

Also, as part of this refactor, we should consider addressing #34 as well. No need to re-filter when all we're doing is changing which slice of `.filtered` to put in `.models`.

**Comment by wraithgar** [comment]
Here is paged collection https://github.com/wraithgar/paged-collection

Discussion is now open and welcome for that repo, we can move it to this org as `ampersand-paged-collection` if we like it.

**Comment by wraithgar** [comment]
https://github.com/AmpersandJS/ampersand-paginated-subcollection and https://github.com/AmpersandJS/ampersand-filtered-subcollection now exist.
